### ISSUE TITLE
Site disappears with "sound" query

### ISSUE THREAD

**Issue by jarwino** [shaynak/taylor-swift#1]
When "sound" is entered as the search query, the site disappears and the app appears to crash.
<img width="1357" alt="Screen Shot 2022-12-20 at 2 40 53 PM" src="https://user-images.githubusercontent.com/7981577/208752698-bcc7ad99-a690-46b8-894b-664945f48b46.png">

**Comment by shaynak** [comment]
Should now be fixed!
